In [63]:
import scipy.io
from scipy.optimize import linprog
import time

# Load the .mat file
mat_data = scipy.io.loadmat('./LP/instance_medium.mat')

# Extract matrices A, B, and C
A = mat_data.get('A')
B = mat_data.get('B')
C = mat_data.get('C')

# Verify shapes of the matrices
print(f"type of A: {type(A)}")
print(f"type of B: {type(B)}")
print(f"type of C: {type(C)}")
print(f"Shape of A: {A.shape}")
print(f"Shape of B: {B.shape}")
print(f"Shape of C: {C.shape}")
print(f"A: {A}")
print(f"B: {B}")
print(f"C: {C}")


type of A: <class 'numpy.ndarray'>
type of B: <class 'numpy.ndarray'>
type of C: <class 'numpy.ndarray'>
Shape of A: (1, 100000)
Shape of B: (50, 100000)
Shape of C: (50, 1)
A: [[54 81 75 ... 77 83 14]]
B: [[73 47 49 ... 20 82 11]
 [96 72 96 ... 43 82 86]
 [14 20 68 ... 13 53 56]
 ...
 [32 42 30 ... 43 95 56]
 [93 76 95 ... 22 85 93]
 [45 56 58 ... 19 85 69]]
C: [[2680554]
 [5100371]
 [2254902]
 [6830696]
 [8516091]
 [3627679]
 [1144172]
 [1300470]
 [9942699]
 [4776806]
 [9119356]
 [8528564]
 [9570228]
 [6920412]
 [6467250]
 [2127474]
 [9170929]
 [4947165]
 [9478746]
 [3581730]
 [2369114]
 [1708640]
 [9432686]
 [8359428]
 [9894115]
 [8751678]
 [5924319]
 [2214708]
 [2007516]
 [2906428]
 [1686951]
 [4403697]
 [9334083]
 [4211271]
 [6035979]
 [5064067]
 [4694147]
 [3766720]
 [8469522]
 [1250489]
 [6277403]
 [6814798]
 [8070130]
 [3237071]
 [6240135]
 [3460445]
 [2497821]
 [4115520]
 [2866468]
 [6805510]]


In [64]:

# Linear programming problem formulation
# Objective function: maximize A @ x -> equivalent to minimize -A @ x
c = -(A.astype(int).flatten())
c

array([-54, -81, -75, ..., -77, -83, -14])

In [65]:

# Constraints: B @ x <= C, x >= 0
A_ub = B
b_ub = C.flatten()

# Bounds for variables: x_i >= 0
x_bounds = [(0, None) for _ in range(A.shape[1])]



In [66]:
start = time.time()
# Solve the linear programming problem
result = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=x_bounds, method='interior-point')
end = time.time()
print(f"Time taken: {end - start:.4f} seconds")
# Print the result
if result.success:
    print("Optimal value found:", -result.fun)
    print("Optimal solution x:", result.x)
else:
    print("Optimization failed:", result.message)

/tmp/ipykernel_2623286/1597076494.py:3: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=x_bounds, method='interior-point')


Time taken: 1.5281 seconds
Optimal value found: 5653427.098690189
Optimal solution x: [1.37125503e-10 1.99513389e-10 2.96369471e-10 ... 2.93221426e-10
 2.86781819e-10 1.18773660e-10]
