In [9]:
import scipy.io
from scipy.optimize import linprog
import time

# Load the .mat file
mat_data = scipy.io.loadmat('./LP/instance_large.mat')

# Extract matrices A, B, and C
A = mat_data.get('A')
B = mat_data.get('B')
C = mat_data.get('C')

# Verify shapes of the matrices
print(f"type of A: {type(A)}")
print(f"type of B: {type(B)}")
print(f"type of C: {type(C)}")
print(f"Shape of A: {A.shape}")
print(f"Shape of B: {B.shape}")
print(f"Shape of C: {C.shape}")
print(f"A: {A}")
print(f"B: {B}")
print(f"C: {C}")


type of A: <class 'numpy.ndarray'>
type of B: <class 'numpy.ndarray'>
type of C: <class 'numpy.ndarray'>
Shape of A: (1, 1000000)
Shape of B: (100, 1000000)
Shape of C: (100, 1)
A: [[37 55 41 ... 16 90 71]]
B: [[ 83  84  44 ...  53  50  62]
 [ 34 100  98 ...  30  62  35]
 [ 54  70  69 ...  38  98  59]
 ...
 [ 23  41  78 ...  96  56  81]
 [ 65  46  90 ...  73  32  64]
 [ 89  78  38 ...  73  67  17]]
C: [[12038658]
 [46825775]
 [41136369]
 [78973223]
 [97898014]
 [37456508]
 [96549190]
 [49164002]
 [38780928]
 [98167087]
 [31221684]
 [55520153]
 [35110394]
 [88383018]
 [72691868]
 [58017731]
 [68871275]
 [48166966]
 [38311167]
 [44648877]
 [55949581]
 [29450436]
 [87375398]
 [92144779]
 [62273035]
 [68659373]
 [39892017]
 [54594935]
 [45637113]
 [52916676]
 [43577361]
 [97984929]
 [89776730]
 [55859370]
 [22167385]
 [65623121]
 [29411588]
 [30400363]
 [23257618]
 [48520708]
 [11265594]
 [26761924]
 [76742201]
 [61686975]
 [32106756]
 [24941538]
 [54100231]
 [46930431]
 [54653924]
 [83822

In [10]:

# Linear programming problem formulation
# Objective function: maximize A @ x -> equivalent to minimize -A @ x
c = -(A.astype(int).flatten())
c

array([-37, -55, -41, ..., -16, -90, -71])

In [11]:

# Constraints: B @ x <= C, x >= 0
A_ub = B
b_ub = C.flatten()

# Bounds for variables: x_i >= 0
x_bounds = [(0, None) for _ in range(A.shape[1])]



In [12]:
start = time.time()
# Solve the linear programming problem
result = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=x_bounds, method='interior-point')
end = time.time()
print(f"Time taken: {end - start:.4f} seconds")
# Print the result
if result.success:
    print("Optimal value found:", -result.fun)
    print("Optimal solution x:", result.x)
else:
    print("Optimization failed:", result.message)

/tmp/ipykernel_2632406/1597076494.py:3: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=x_bounds, method='interior-point')


Time taken: 58.5074 seconds
Optimization failed: The solution does not satisfy the constraints within the required tolerance of 3.16E-04, yet no errors were raised and there is no certificate of infeasibility or unboundedness. Check whether the slack and constraint residuals are acceptable; if not, consider enabling presolve, adjusting the tolerance option(s), and/or using a different method. Please consider submitting a bug report.
